---
hpe_dl380_gen10:
   - type: "BIOS"
     package_name: "firmware-system-u30"
   - type: "iLO 5"
     package_name: "firmware-ilo5"
   - type: "Smart Array"
     package_name: "firmware-smartarray-f7c07bdbbd"

hpe_dl360_gen10:
   - type: "BIOS"
     package_name: "firmware-system-u32"
   - type: "iLO 5"
     package_name: "firmware-ilo5"
   - type: "Smart Array"
     package_name: "firmware-smartarray-f7c07bdbbd"
