---

hpe_dl360_gen10:
   - type: "BIOS"
     package_name: "firmware-system-u32"
   - type: "iLO 5"
     package_name: "firmware-ilo5"
   - type: "Smart Array"
     package_name: "firmware-smartarray-f7c07bdbbd"
   - type: "Advanced Power Capping Microcontroller Firmware"
     package_name: "firmware-powerpic-gen10"
   - type: "NIC Firmware (Intel)
     package_name: "hp-firmware-nic-intel"
   - type: "NIC Firmware (Broadcom)
     package_name: "hp-firmware-nic-broadcom"
   - type: "NIC Firmware (Mellanox)
     package_name: "hp-firmware-nic-mellanox-ethernet-only"

hpe_dl380_gen9:
   - type: "BIOS"
     package_name: "hp-firmware-system-p89"
   - type: "iLO 5"
     package_name: "firmware-ilo4"
   - type: "Smart Array"
     package_name: "hp-firmware-smartarray-ea3138d8e8"
   - type: "NIC Firmware (Broadcom)
     package_name: "hp-firmware-nic-broadcom"

hpe_dl380_gen10:
   - type: "BIOS"
     package_name: "firmware-system-u30"
   - type: "iLO 5"
     package_name: "firmware-ilo5"
   - type: "Smart Array"
     package_name: "firmware-smartarray-f7c07bdbbd"
   - type: "Advanced Power Capping Microcontroller Firmware"
     package_name: "firmware-powerpic-gen10"
   - type: "NIC Firmware (Intel)
     package_name: "hp-firmware-nic-intel"
   - type: "NIC Firmware (Broadcom)
     package_name: "hp-firmware-nic-broadcom"
   - type: "NIC Firmware (Mellanox)
     package_name: "hp-firmware-nic-mellanox-ethernet-only"
